### ISSUE TITLE
Issue on Running

### ISSUE THREAD

**Issue by Bobisback** [SadoP/Anno1800Skyscraper#7]
I am not sure if there are any debug options or not. But for some reason it is closing after creating the first images. 

I am trying to do this on the following ad file. 
[https://1drv.ms/u/s!Ao-QRXX08r9vjxpqAL5M1kIwyoC_?e=8fIOSu](url)

When I run it it makes the initial images, then starts the progress bar, then exits.
Anno1800Skyscraper) C:\Users\Bobisback\Downloads\Anno1800Skyscraper-main>python main.py -d ./layouts/LargeInvestorBlock -e 5000 -c .04

Total inhabitants: 89438
  0%|                                                                                                                          | 0/5000 [00:00<?, ?epoch/s]

(Anno1800Skyscraper) C:\Users\Bobisback\Downloads\Anno1800Skyscraper-main>

Not sure how to troubleshoot it from here. Any thoughts?

**Comment by SadoP** [comment]
[LargeInvestorBlock.tar.gz](https://github.com/SadoP/Anno1800Skyscraper/files/13452330/LargeInvestorBlock.tar.gz)

I can't replicate the problem on my machine. I have successfully run the tool with the file you provided, so at least I can give that one to you. If you want me to troubleshoot your error further, I will need more information. A stacktrace would do fine, or open a python console and run the main.py script with your parameters as substitutes for the command line parameters and give me the errors that gives you.
